version: '3.8'

services:
  # FastAPI application
  api:
    build: .
    container_name: surgeonmatch-api
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/surgeonmatch
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=true
      - API_KEY_HEADER=X-API-Key
      - API_PREFIX=/api/v1
      - SECRET_KEY=your-super-secret-key-change-in-production
      - RATE_LIMIT=100
      - RATE_LIMIT_PERIOD=60
    depends_on:
      - db
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: surgeonmatch-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=surgeonmatch
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: surgeonmatch-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
